[tool.poetry]
name = "4k120"
version = "0.1.0"
description = "Set resolution and refresh rate to 4K@120Hz"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[tool.pylint]
disable = "invalid-name"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
