[tool.poetry]
name = "4k120"
version = "0.2.0"
description = "Set resolution and refresh rate to 4K @ 120Hz"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
pywin32 = "^306"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.4.0"

[tool.pylint]
disable = [
    "broad-exception-caught",
    "c-extension-no-member",
    "import-error",
    "invalid-name",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
